### ISSUE TITLE
Using autoNumeric('set', value) doesn't update hidden input

### ISSUE THREAD

**Issue by adailey14** [randoum/autonumeric-rails#6]
I create an input field like this:
= text_field_tag('test', 0, { data: {autonumeric: {aSign: '$ ', mDec: 0, wEmpty: 'sign', lZero: 'deny'}}})

I then update the value from javascript like this:
$("#test").autoNumeric('set', 4000)

The number changes to $ 4000 in the visible formatted input field as expected.
But the value of the hidden input does not change - so when the form is submitted the correct value does not get submitted.

**Comment by randoum** [comment]
You must update the value by using `val()` like this :
```
$("#test").val('4000')
```

**Comment by paullimzw** [comment]
i was facing the same issue of getting autonumeric functionality to kick in after updating value via javascript .val() on a rails tex_field. Visually, i used js focusout() to convert the field contents to autonumeric format. However, the same issue happened and the hidden value was not updates.

Changing to use .blur() instead of .focusout() fixed it.

**Comment by tirdadc** [comment]
When I use `val()` directly on a currency field, it loses the `$` sign:

``` erb
<%= text_field_tag :price, 0, data: { autonumeric: { aSign: '$', mDec: 0 } } %>
```

EDIT: Never mind, this is because we're using some [ancient version](https://github.com/randoum/autonumeric-rails) of this plugin that require `init` to be called before a `set`.
